version: "3"
networks:
  dgraph:
services:
  zero:
    image: dgraph/dgraph:test
    volumes:
      - data-volume:/dgraph
    ports:
      - 6080:6080
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == myvm1
    command: dgraph zero --port_offset -2000 --my=zero:5080 --replicas 3
  server_1:
    image: dgraph/dgraph:test
    hostname: "server_1"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == myvm1
    command: dgraph server --my=server_1:7080 --memory_mb=2048 --zero=zero:5080 --debugmode
  server_2:
    image: dgraph/dgraph:test
    hostname: "server_2"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == myvm2
    command: dgraph server --my=server_2:7081 --memory_mb=2048 --zero=zero:5080 --debugmode -o 1
  server_3:
    image: dgraph/dgraph:test
    hostname: "server_3"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == myvm3
    command: dgraph server --my=server_3:7082 --memory_mb=2048 --zero=zero:5080 --debugmode -o 2
volumes:
  data-volume:
